### ISSUE TITLE
One-step build

### ISSUE THREAD

**Issue by ethanpailes** [wgallo3/MockRoutingPack#1]
It would be nice to have a single script that could do everything that you need to build a safe_launcher with mock routing. A thumbnail sketch of how to do this is:

- [x] Add a git submodule for both safe_core (now called safe_client_libs on github) and safe_launcher pinned to some known-good commits. This will make sure that updates to the upstream repos do not break anything.
- [x] Write a script that checks to make sure that node, npm, cargo, and rustc are installed and have the right versions. If any checks fail the script should print links to the best place to install the various tools from.
- [x] Actually run all of the build steps (cargo build, copying the build artifact, npm install, ...).

I have a lot on my plate at the moment, so I won't be able to get to this soon, but I can certainly provide advice if anyone wants to tackle it. I can also just attack it when things cool down a little for me.

**Comment by whiteoutmashups** [comment]
i guess, I'm pretty content with providing the downloadable programs for people instead though. The people who this is aimed at won't know how to use a script and have no interest building it themselves

**Comment by ethanpailes** [comment]
That's reasonable. It would still be a nice thing to have for developers. I guess the title of this repo made me think you intended it more for developers than interested community members. Perhaps we should make a separate repo that contains a one-step build for a mock routing version of the launcher. I've starting hacking around a bit, and I'll probably open a PR at some point, but feel free to say that you would rather it go in a separate repo.
